repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs
  - id: check-toml
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.263
  hooks:
  - id: ruff
  args: [ --fix, --show-fixes, --exit-non-zero-on-fix]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.14
  hooks:
  - id: validate-pyproject
